process.env.REFLECT_DISABLE_LOG_ECHO = process.env.REFLECT_DISABLE_LOG_ECHO ?? '1';
process.env.REFLECT_DISABLE_DAEMON = process.env.REFLECT_DISABLE_DAEMON ?? '1';
process.env.REFLECT_STABILITY_WINDOW_MS = process.env.REFLECT_STABILITY_WINDOW_MS ?? '5';
process.env.REFLECT_STABILITY_POLL_MS = process.env.REFLECT_STABILITY_POLL_MS ?? '2';
process.env.REFLECT_STABILITY_MAX_WAIT_MS = process.env.REFLECT_STABILITY_MAX_WAIT_MS ?? '25';
